# Generated by Django 5.2.8 on 2025-12-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='his',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.add')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.product')),
            ],
        ),
    ]
