# Generated by Django 5.2.8 on 2025-12-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_his'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='his',
            new_name='History',
        ),
    ]
